In [1]:
import numpy as np
import pandas as pd

In [8]:
data = pd.read_csv('customer_data.csv')
data.head(2)

   Customer ID  CIBIL Score Monthly Income (₹) Loan Status
0         1001          610            ₹15,000    Rejected
1         1002          760            ₹55,000    Approved

In [9]:
def clean_income(x):
    output = float(x.replace('₹','').replace(',',''))
    return output

data['Monthly Income (₹)'] = data['Monthly Income (₹)'].apply(clean_income)
data.head()

   Customer ID  CIBIL Score  Monthly Income (₹) Loan Status
0         1001          610             15000.0    Rejected
1         1002          760             55000.0    Approved
2         1003          670             35000.0    Approved
3         1004          775             48000.0    Approved
4         1005          735             32000.0    Approved

In [ ]:
def predict(df, new_customer):
    distances = []
    for index, row in df.iterrows():
        distance = np.sqrt((row['CIBIL Score'] - new_customer[0])**2 + (row['Monthly Income (₹)'] - new_customer[0])**2)
        distances.append((index, distance))

    # sort it 
    

    return distances

In [14]:
new_customer = np.array([600,28])

distances = predict(data, new_customer)
distances

[(0, np.float64(14400.003472221804)),
 (1, np.float64(54400.23529360879)),
 (2, np.float64(34400.07122085651)),
 (3, np.float64(47400.32304742237)),
 (4, np.float64(31400.290205665297)),
 (5, np.float64(29400.170067535324)),
 (6, np.float64(37400.021390368216)),
 (7, np.float64(41400.02445651452)),
 (8, np.float64(29400.205781592755)),
 (9, np.float64(67400.24035565452)),
 (10, np.float64(89400.29586080798)),
 (11, np.float64(11400.01754384615)),
 (12, np.float64(19400.208761763362)),
 (13, np.float64(49400.14574877285)),
 (14, np.float64(24400.295080182943)),
 (15, np.float64(47400.076213018896)),
 (16, np.float64(37400.34224442338)),
 (17, np.float64(30400.19901250648)),
 (18, np.float64(27400.04562039998)),
 (19, np.float64(74400.32526810619)),
 (20, np.float64(16400.1493895635)),
 (21, np.float64(34400.34919880902)),
 (22, np.float64(23400.09027760363)),
 (23, np.float64(44400.190314907435)),
 (24, np.float64(27400.029197064738)),
 (25, np.float64(71400.25280067291)),
 (26, np.float64(44400.253377655405)),
 (27, np.float64(37400.040441154604)),
 (28, np.float64(11400.631561453076)),
 (29, np.float64(28400.158890400595)),
 (30, np.float64(49400.25910863221)),
 (31, np.float64(9400.531899844817)),
 (32, np.float64(8400.005952378844)),
 (33, np.float64(14400.22222050757)),
 (34, np.float64(41400.1207727707)),
 (35, np.float64(64400.310558257406)),
 (36, np.float64(9400.0)),
 (37, np.float64(39400.06218269205)),
 (38, np.float64(17400.103447968348)),
 (39, np.float64(31400.05732478844)),
 (40, np.float64(39400.32487175708)),
 (41, np.float64(44400.09121612252)),
 (42, np.float64(30400.118832004588)),
 (43, np.float64(59400.33669938244)),
 (44, np.float64(7401.520114138717)),
 (45, np.float64(7400.027026977672)),
 (46, np.float64(32400.30246772397)),
 (47, np.float64(21400.149532187854)),
 (48, np.float64(26400.12121184295)),
 (49, np.float64(31400.101910662648)),
 (50, np.float64(79400.27770732291)),
 (51, np.float64(25400.059547174293)),
 (52, np.float64(54400.33180045872)),
 (53, np.float64(99400.31438582073)),
 (54, np.float64(29400.24489693921)),
 (55, np.float64(35400.296962031265)),
 (56, np.float64(54400.045036746065)),
 (57, np.float64(51400.315174130985)),
 (58, np.float64(41400.349032345126)),
 (59, np.float64(34400.0523255416))]

In [10]:
for index, row in data.iterrows():
    print(index, row)

0 Customer ID               1001
CIBIL Score                610
Monthly Income (₹)     15000.0
Loan Status           Rejected
Name: 0, dtype: object
1 Customer ID               1002
CIBIL Score                760
Monthly Income (₹)     55000.0
Loan Status           Approved
Name: 1, dtype: object
2 Customer ID               1003
CIBIL Score                670
Monthly Income (₹)     35000.0
Loan Status           Approved
Name: 2, dtype: object
3 Customer ID               1004
CIBIL Score                775
Monthly Income (₹)     48000.0
Loan Status           Approved
Name: 3, dtype: object
4 Customer ID               1005
CIBIL Score                735
Monthly Income (₹)     32000.0
Loan Status           Approved
Name: 4, dtype: object
5 Customer ID               1006
CIBIL Score                700
Monthly Income (₹)     30000.0
Loan Status           Approved
Name: 5, dtype: object
6 Customer ID               1007
CIBIL Score                640
Monthly Income (₹)     38000.0
Loan Status           Approved
Name: 6, dtype: object
7 Customer ID               1008
CIBIL Score                645
Monthly Income (₹)     42000.0
Loan Status           Approved
Name: 7, dtype: object
8 Customer ID               1009
CIBIL Score                490
Monthly Income (₹)     30000.0
Loan Status           Rejected
Name: 8, dtype: object
9 Customer ID               1010
CIBIL Score                780
Monthly Income (₹)     68000.0
Loan Status           Approved
Name: 9, dtype: object
10 Customer ID               1011
CIBIL Score                830
Monthly Income (₹)     90000.0
Loan Status           Approved
Name: 10, dtype: object
11 Customer ID               1012
CIBIL Score                620
Monthly Income (₹)     12000.0
Loan Status           Rejected
Name: 11, dtype: object
12 Customer ID               1013
CIBIL Score                510
Monthly Income (₹)     20000.0
Loan Status           Rejected
Name: 12, dtype: object
13 Customer ID               1014
CIBIL Score                480
Monthly Income (₹)     50000.0
Loan Status           Rejected
Name: 13, dtype: object
14 Customer ID               1015
CIBIL Score                480
Monthly Income (₹)     25000.0
Loan Status           Rejected
Name: 14, dtype: object
15 Customer ID               1016
CIBIL Score                515
Monthly Income (₹)     48000.0
Loan Status           Rejected
Name: 15, dtype: object
16 Customer ID               1017
CIBIL Score                760
Monthly Income (₹)     38000.0
Loan Status           Approved
Name: 16, dtype: object
17 Customer ID               1018
CIBIL Score                710
Monthly Income (₹)     31000.0
Loan Status           Approved
Name: 17, dtype: object
18 Customer ID               1019
CIBIL Score                650
Monthly Income (₹)     28000.0
Loan Status           Rejected
Name: 18, dtype: object
19 Customer ID               1020
CIBIL Score                820
Monthly Income (₹)     75000.0
Loan Status           Approved
Name: 19, dtype: object
20 Customer ID               1021
CIBIL Score                530
Monthly Income (₹)     17000.0
Loan Status           Rejected
Name: 20, dtype: object
21 Customer ID               1022
CIBIL Score                755
Monthly Income (₹)     35000.0
Loan Status           Approved
Name: 21, dtype: object
22 Customer ID               1023
CIBIL Score                665
Monthly Income (₹)     24000.0
Loan Status           Rejected
Name: 22, dtype: object
23 Customer ID               1024
CIBIL Score                730
Monthly Income (₹)     45000.0
Loan Status           Approved
Name: 23, dtype: object
24 Customer ID               1025
CIBIL Score                560
Monthly Income (₹)     28000.0
Loan Status           Rejected
Name: 24, dtype: object
25 Customer ID               1026
CIBIL Score                790
Monthly Income (₹)     72000.0
Loan Status           Approved
Name: 25, dtype: object
26 Customer ID               1027
CIBIL Score                750
Monthly Income (₹)     45000.0
Loan Status           Approved
Name: 26, dtype: object
27 Customer ID               1028
CIBIL Score                545
Monthly Income (₹)     38000.0
Loan Status           Rejected
Name: 27, dtype: object
28 Customer ID               1029
CIBIL Score                480
Monthly Income (₹)     12000.0
Loan Status           Rejected
Name: 28, dtype: object
29 Customer ID               1030
CIBIL Score                695
Monthly Income (₹)     29000.0
Loan Status           Rejected
Name: 29, dtype: object
30 Customer ID               1031
CIBIL Score                760
Monthly Income (₹)     50000.0
Loan Status           Approved
Name: 30, dtype: object
31 Customer ID               1032
CIBIL Score                500
Monthly Income (₹)     10000.0
Loan Status           Rejected
Name: 31, dtype: object
32 Customer ID               1033
CIBIL Score                590
Monthly Income (₹)      9000.0
Loan Status           Rejected
Name: 32, dtype: object
33 Customer ID               1034
CIBIL Score                520
Monthly Income (₹)     15000.0
Loan Status           Rejected
Name: 33, dtype: object
34 Customer ID               1035
CIBIL Score                500
Monthly Income (₹)     42000.0
Loan Status           Rejected
Name: 34, dtype: object
35 Customer ID               1036
CIBIL Score                800
Monthly Income (₹)     65000.0
Loan Status           Approved
Name: 35, dtype: object
36 Customer ID               1037
CIBIL Score                600
Monthly Income (₹)     10000.0
Loan Status           Rejected
Name: 36, dtype: object
37 Customer ID               1038
CIBIL Score                530
Monthly Income (₹)     40000.0
Loan Status           Rejected
Name: 37, dtype: object
38 Customer ID               1039
CIBIL Score                540
Monthly Income (₹)     18000.0
Loan Status           Rejected
Name: 38, dtype: object
39 Customer ID               1040
CIBIL Score                660
Monthly Income (₹)     32000.0
Loan Status           Approved
Name: 39, dtype: object
40 Customer ID               1041
CIBIL Score                760
Monthly Income (₹)     40000.0
Loan Status           Approved
Name: 40, dtype: object
41 Customer ID               1042
CIBIL Score                510
Monthly Income (₹)     45000.0
Loan Status           Rejected
Name: 41, dtype: object
42 Customer ID               1043
CIBIL Score                685
Monthly Income (₹)     31000.0
Loan Status           Approved
Name: 42, dtype: object
43 Customer ID               1044
CIBIL Score                800
Monthly Income (₹)     60000.0
Loan Status           Approved
Name: 43, dtype: object
44 Customer ID               1045
CIBIL Score                450
Monthly Income (₹)      8000.0
Loan Status           Rejected
Name: 44, dtype: object
45 Customer ID               1046
CIBIL Score                580
Monthly Income (₹)      8000.0
Loan Status           Rejected
Name: 45, dtype: object
46 Customer ID               1047
CIBIL Score                740
Monthly Income (₹)     33000.0
Loan Status           Approved
Name: 46, dtype: object
47 Customer ID               1048
CIBIL Score                520
Monthly Income (₹)     22000.0
Loan Status           Rejected
Name: 47, dtype: object
48 Customer ID               1049
CIBIL Score                680
Monthly Income (₹)     27000.0
Loan Status           Rejected
Name: 48, dtype: object
49 Customer ID               1050
CIBIL Score                520
Monthly Income (₹)     32000.0
Loan Status           Rejected
Name: 49, dtype: object
50 Customer ID               1051
CIBIL Score                810
Monthly Income (₹)     80000.0
Loan Status           Approved
Name: 50, dtype: object
51 Customer ID               1052
CIBIL Score                655
Monthly Income (₹)     26000.0
Loan Status           Rejected
Name: 51, dtype: object
52 Customer ID               1053
CIBIL Score                790
Monthly Income (₹)     55000.0
Loan Status           Approved
Name: 52, dtype: object
53 Customer ID               1054
CIBIL Score                850
Monthly Income (₹)    100000.0
Loan Status           Approved
Name: 53, dtype: object
54 Customer ID               1055
CIBIL Score                720
Monthly Income (₹)     30000.0
Loan Status           Approved
Name: 54, dtype: object
55 Customer ID               1056
CIBIL Score                745
Monthly Income (₹)     36000.0
Loan Status           Approved
Name: 55, dtype: object
56 Customer ID               1057
CIBIL Score                530
Monthly Income (₹)     55000.0
Loan Status           Rejected
Name: 56, dtype: object
57 Customer ID               1058
CIBIL Score                780
Monthly Income (₹)     52000.0
Loan Status           Approved
Name: 57, dtype: object
58 Customer ID               1059
CIBIL Score                770
Monthly Income (₹)     42000.0
Loan Status           Approved
Name: 58, dtype: object
59 Customer ID               1060
CIBIL Score                540
Monthly Income (₹)     35000.0
Loan Status           Rejected
Name: 59, dtype: object